const container = document.getElementById('container');


//testrun for one div//
// let div = document.createElement('div');
// container.appendChild(div);

// div.setAttribute('style', 'width:16px', 'height:16px', 'border:2px solid');


function makeDivs(numDivs) {
    for(let i=0;i<=numDivs;i++) {
        let box = document.createElement('div');
        box.classList.add('square');
        container.appendChild(box);

    }
}
makeDivs(256);

const square = document.querySelectorAll('.square');

//use forEach() to iterate through the Node List generated by querySelectorAll//
square.forEach(square => {

square.addEventListener('mouseover', function(){
    square.style.backgroundColor = 'red';
});

square.addEventListener('mouseout', function() {
    square.style.backgroundColor = 'initial';
});
    
});
    